//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.bananaframework.net.View.CNT {
    
    
    public partial class _1000 {
        
        /// <summary>
        /// _txtMBR_CD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TextBox _txtMBR_CD;
        
        /// <summary>
        /// _txtMBR_NM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TextBox _txtMBR_NM;
        
        /// <summary>
        /// _txtCNTR_HPNO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TextBox _txtCNTR_HPNO;
        
        /// <summary>
        /// _txtCNTR_NM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TextBox _txtCNTR_NM;
        
        /// <summary>
        /// _btnSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.Button _btnSearch;
        
        /// <summary>
        /// _btnNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.Button _btnNew;
        
        /// <summary>
        /// FixedGrid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.FixedGrid FixedGrid1;
        
        /// <summary>
        /// REGDT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.BoundDataField REGDT;
        
        /// <summary>
        /// MBR_CD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TemplateField MBR_CD;
        
        /// <summary>
        /// MBR_NM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.BoundDataField MBR_NM;
        
        /// <summary>
        /// CNTR_NM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.BoundDataField CNTR_NM;
        
        /// <summary>
        /// CNTR_HPNO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.BoundDataField CNTR_HPNO;
        
        /// <summary>
        /// SAUP_NO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.BoundDataField SAUP_NO;
    }
}
