//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.bananaframework.net.FileUpload {
    
    
    public partial class Demo {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// FileUpload1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.FileUpload FileUpload1;
        
        /// <summary>
        /// _btnUpload control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.Button _btnUpload;
        
        /// <summary>
        /// _btnQuery control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.Button _btnQuery;
        
        /// <summary>
        /// _btnApply_01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button _btnApply_01;
        
        /// <summary>
        /// _rblButtonsShowAdd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.RadioButtonList _rblButtonsShowAdd;
        
        /// <summary>
        /// _rblButtonsShowRemoveAllFiles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.RadioButtonList _rblButtonsShowRemoveAllFiles;
        
        /// <summary>
        /// _rblButtonsShowRemoveSelectedFiles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.RadioButtonList _rblButtonsShowRemoveSelectedFiles;
        
        /// <summary>
        /// _rblButtonsShowStartUpload control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.RadioButtonList _rblButtonsShowStartUpload;
        
        /// <summary>
        /// _txtDownloadManagerDefaultFolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TextBox _txtDownloadManagerDefaultFolder;
        
        /// <summary>
        /// _rblDownloadManagerEnableCancelButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.RadioButtonList _rblDownloadManagerEnableCancelButton;
        
        /// <summary>
        /// _rblDownloadManagerEnableChangeFolderButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.RadioButtonList _rblDownloadManagerEnableChangeFolderButton;
        
        /// <summary>
        /// _rblDownloadManagerEnableOpenFolderButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.RadioButtonList _rblDownloadManagerEnableOpenFolderButton;
        
        /// <summary>
        /// _ddlDownloadManagerRootFolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.DropDownList _ddlDownloadManagerRootFolder;
        
        /// <summary>
        /// _txtLimitIndividualFileLength control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TextBox _txtLimitIndividualFileLength;
        
        /// <summary>
        /// _ddlLimitIndividualFileUnit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.DropDownList _ddlLimitIndividualFileUnit;
        
        /// <summary>
        /// _txtLimitPermittedExtensions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TextBox _txtLimitPermittedExtensions;
        
        /// <summary>
        /// _txtLimitTotalFilesCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TextBox _txtLimitTotalFilesCount;
        
        /// <summary>
        /// _txtLimitTotalFilesLength control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TextBox _txtLimitTotalFilesLength;
        
        /// <summary>
        /// _ddlLimitTotalFilesUnit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.DropDownList _ddlLimitTotalFilesUnit;
        
        /// <summary>
        /// _ddlFileNameFormat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.DropDownList _ddlFileNameFormat;
        
        /// <summary>
        /// _ddlIndividualFileClickMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.DropDownList _ddlIndividualFileClickMode;
        
        /// <summary>
        /// _txtUploadPath control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TextBox _txtUploadPath;
        
        /// <summary>
        /// _rblUseBananaAgent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.RadioButtonList _rblUseBananaAgent;
        
        /// <summary>
        /// _btnApply_02 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button _btnApply_02;
    }
}
