//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.bananaframework.net.View.BAS {
    
    
    public partial class _1000 {
        
        /// <summary>
        /// _txtCODE_NAME1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TextBox _txtCODE_NAME1;
        
        /// <summary>
        /// _txtCODE_NAME2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.TextBox _txtCODE_NAME2;
        
        /// <summary>
        /// _btnSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.Button _btnSearch;
        
        /// <summary>
        /// _btnNew1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.Button _btnNew1;
        
        /// <summary>
        /// _btnNew2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.Button _btnNew2;
        
        /// <summary>
        /// FixedGrid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.FixedGrid FixedGrid1;
        
        /// <summary>
        /// FixedGrid2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BANANA.Web.Controls.FixedGrid FixedGrid2;
    }
}
